Detegr/rust-ctrlc

- src/lib.rs
This appears to fix #3. I'm not sure, but it might also cause some signals to get dropped? Also I'm not sure what Ordering to use for this so I used `Relaxed` because that's what the reads/writes to `DONE` use.
So far I've only tested it in linux, but I hope to test it in windows too.
> Reset DONE status after a successful wait

- src/lib.rs
```
$ rustc --version
rustc 1.8.0-dev (2d14b3920 2016-02-20)
```
```
Compiling ctrlc v1.1.0
src/lib.rs:49:5: 49:15 error: attribute should be applied to struct or enum [E0517]
src/lib.rs:49     #[repr(C)]
^~~~~~~~~~
src/lib.rs:49:5: 49:15 help: run `rustc --explain E0517` to see a detailed explanation
src/lib.rs:49:5: 49:15 error: attribute should be applied to struct or enum [E0517]
src/lib.rs:49     #[repr(C)]
^~~~~~~~~~
src/lib.rs:49:5: 49:15 help: run `rustc --explain E0517` to see a detailed explanation
error: aborting due to previous error
```
> remove fn #[repr(C)]

- README.md
- examples/readme_example.rs
- examples/simple.rs
- src/lib.rs
The original export scheme was... curious, to say the least.
> Export straight functions rather than a singleton struct therewith

- src/lib.rs
Started to use the crate in my project and noticed that `std::error::Errror` hadn't been implemented for `ctrlc::Error`. Consider this a workable first pass and let me know if you would like any changes to anything.
Thank you.
> Implement std::error::Error for ctrlc::Error

- Cargo.toml
- src/lib.rs
- src/tests.rs
This tries to address some problems with how errors are currently being handled.
Changes:
- Avoid panics.
- Cleanup resources on error.
- Document errors, #22.
- Document `SIGTERM`, #21.
- `no_run` examples.
- Use [nix](https://github.com/nix-rust/nix) crate instead of raw [libc](https://github.com/rust-lang/libc) bindings.
- Use [std::io::Error](https://doc.rust-lang.org/std/io/struct.Error.html) for system errors and errno.
- Simplify Error enum.
- Use [sigaction()](http://man7.org/linux/man-pages/man2/sigaction.2.html) instead of [signal()](http://man7.org/linux/man-pages/man7/signal.7.html), see [this](https://stackoverflow.com/a/232711/4597055).
- Testing using custom test harness.
- Run tests on a secondary console on windows.
- Workaround for the fact that …
> Improved error handling and documentation

- appveyor.yml
Possibly fix sporadic download failure on AppVeyor
> Surround rustup download with appveyor-retry

- Cargo.toml
The current version on crates.io is not building on openbsd and nix 0.11.0 includes a fix for openbsd 6.3. :)
If possible, could you please release a new version containing this patch?
> Fix build on openbsd 6.3

- Cargo.toml
- src/lib.rs
This bumps the nix dependency and resolves the deprecation warning about ATOMIC_BOOL_INIT.
Resolves #48
> Fix nix build failure on openbsd

- Cargo.toml
nix 0.14 contains fix for nix-rust/nix#1057
Without this arm builds are failing.
> bump nix to 0.14

- src/lib.rs
Slightly improves the debuggability.
> Add a name to the thread

- src/error.rs
`write!(f, "Ctrl-C error: {}", self)` infinitely recurses. This extracts the contents of `description` to a private `describe` function to avoid calling the deprecated `description`.
> Fix unconditional recursion in <ctrlc::Error as fmt::Display>::fmt

- Cargo.toml
- src/platform/unix/mod.rs
`pipe2` is no longer available on macOS, so I implemented it manually using `pipe` and `fcntl` similar to how it was implemented in nix 0.17.
> Update nix to 0.18

- .travis.yml
Travis CI seems failed on `master` due to `rustfmt` install failure: https://travis-ci.org/github/Detegr/rust-ctrlc/builds/734809619
This patch fixes that failure by installing stable `rustfmt` via `rustup` instead of installing `rustfmt-nightly` from the source.
(This will also hopefully reduce Travis CI's run time.)
> Fix Travis CI failure

- Cargo.toml
- README.md
- examples/issue_46_example.rs
- examples/readme_example.rs
- src/error.rs
- src/lib.rs
- src/platform/unix/mod.rs
- src/platform/windows/mod.rs
- src/signal.rs
- src/tests.rs
Since #69, the minimum Rust version supported by this crate is 1.36 (because [nix 0.18 use `std::mem::MaybeUninit`](https://github.com/nix-rust/nix/pull/1214) that stabilized in 1.36), so we can migrate to the 2018 edition without breakage.
(This patch was created primarily by running [`cargo fix --editon`](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition), removing needless `extern crate`, and removing `self::` prefix from external crate paths.)
> Migrate to Rust 2018

- Cargo.toml
Right now there is no preview on crates.io: https://crates.io/crates/ctrlc
With this PR (and the next release that contains this change) crates.io will show the README.md as preview which will attract more users.
> add "readme"-key to Cargo.toml (for crates.io preview)

- src/platform/unix/mod.rs
If you have the `termination` feature enabled and close the terminal (its window) with the X button, `SIGHUP` is sent to the process but `ctrlc` doesn't handle it so no graceful shutdown is done in that case but I would expect the `termination` feature to be able to detect that because pressing the X button to terminate an application is definitely a common kind of termination. Also, I believe on Windows this already works because when the window is X-ed, `CTRL_CLOSE_EVENT` is sent which `ctrlc` seems to handle. This means on Windows, the handler is invoked on X but on Linux (and very likely macOS), it is not. So this fixes inconsistent behavior.
> Check for SIGHUP

- Cargo.toml
This reduces compilation time slightly, and removes the memoffset crate as an indirect dependency.
> Upgrade nix to 0.24, limit features

- src/lib.rs
- src/platform/unix/mod.rs
1. Compare_and_swap was deprecated thus I changed it over to compare_exchange while retaining the same functionality.
2. Unused variable warning fixed.
> Fixed two warnings in the build

- Cargo.toml
- src/platform/windows/mod.rs
- src/tests.rs
- Implemented #85 
Most function calls and their signatures stayed the same. Only some types changed.
> Migrate from `winapi` to `windows-sys`

- src/platform/unix/mod.rs
Like Haiku or Apple platform, AIX also doesn't have pipe2.
> Support AIX operating system

- src/platform/unix/mod.rs
It seems reasonable to try to restore the original handler, before returning `MultopleHandlers` on Unix.
Aligns with the logic for the case when `sigaction` fails - the code is trying to restore old handlers for any previously affected signals.
I could not figure out how to check this behavior in the test.
`sigaction` is supposed to report the current handler without updating it, if passed `NULL`.
From https://man7.org/linux/man-pages/man2/sigaction.2.html:
If act is non-NULL, the new action for signal signum is installed
from act.  If oldact is non-NULL, the previous action is saved in
oldact.
Not sure if this is true for other Unixes.
But [`nix::sys::signal::sigaction`](https://docs.rs/nix/latest/nix/sys/signal/fn.sigaction.html) does not seem to allow this particular usage, as it will …
> unix: Restore old handler when returning MultipleHandlers

- src/platform/unix/mod.rs
This adds support for QNX Neutrino 7.1 (https://blackberry.qnx.com/en/products/foundation-software/qnx-rtos).
> Add support for QNX Neutrino

- Cargo.toml
This pulls in https://github.com/nix-rust/nix/pull/2049 and thus which will unlock https://github.com/rust-lang/rust/pull/111769.
If you merge this can you please then cut a new patch release? :pray:
> Bump to nix 0.27

- src/platform/unix/mod.rs
Since v3.4.3 (https://github.com/Detegr/rust-ctrlc/pull/114, cc @saethlin), this crate failed to build on macOS (and iOS, Haiku, etc.)
Fixes #115
```
error[E0308]: mismatched types
--> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ctrlc-3.4.3/src/platform/unix/mod.rs:50:33
|
50  |             .and_then(|_| fcntl(pipe.0, FcntlArg::F_SETFD(FdFlag::FD_CLOEXEC)))
|                           ----- ^^^^^^ expected `i32`, found `OwnedFd`
|                           |
|                           arguments to this function are incorrect
|
note: function defined here
--> /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nix-0.28.0/src/fcntl.rs:600:8
|
600 | pub fn fcntl(fd: RawFd, arg: FcntlArg) -> Result<c_int> {
|        ^^^^^
error[E0308]: mismatched types …
```
> Fix build error on macOS

- src/lib.rs
This PR proposes to allow handling errors on spawning a thread by users. By this change, user applications can determine what to do when `Ctrl+C` hook could not be set:
- Do some clean up before exiting
- Just ignore setting Ctrl+C hook and continue
I know that Rust provides an escape hatch `std::panic::catch_unwind`, but it is only available when `panic = "abort"` and not an idiomatic error handling.
> Do not crash on thread spawn error

- src/platform/unix/mod.rs
At least compilation-wise (it's unclear whether installing the handler on these platforms make sense at all, but it should be the same situation as on iOS).
Haven't tested this.
> Add support for tvOS, visionOS and watchOS
